### ISSUE TITLE
Poetry: Python version

### ISSUE THREAD

**Issue by j-woz** [ANL-Braid/DB#21]
Currently does not allow my Anaconda at 3.9, what is the best fix for this?

[issue-21-diff.txt](https://github.com/ANL-Braid/DB/files/8044135/issue-21-diff.txt)

**Comment by jimPruyne** [comment]
I'll have to give this a try. The file pyproject.toml currently pins to python 3.8. We might address this by making the pyproject file more flexible on the python version.

Alternatively, we probably should just pick a python version and target our development against that. I had picked 3.8 somewhat arbitrarily. @j-woz If` you have a preference for 3.9 or any other version, we can try to just agree on that.

**Comment by jimPruyne** [comment]
I was able to get this going by running:
```
poetry env use python3.9
```

This worked for me on theta login nodes. However, mpich doesn't seem to be available there (at least for me), so I had to remove `mpi4py` from `pyproject.toml` before running poetry install.

**Comment by j-woz** [comment]
I'm not sure what happened but this isn't a problem any more.
